apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-vpc
  namespace: todo-app
  labels:
    app: todo-application
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi