apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: todo-app
  labels:
    app: todo-application
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3JkMTIz
  MYSQL_PASSWORD: dXNlcnBhc3N3b3JkMTIz
